### ISSUE TITLE
Code new DAPs in a spreadsheet

### ISSUE THREAD

**Issue by korenmiklos** [REStud/guidance#4]
https://docs.google.com/spreadsheets/d/11lua0_5iE-ioX0H-90oUM-ZdfYkZCMBHjAHIpC2ZYds/edit#gid=0

Reading the DAP, please code if that rule is "verified" (only if journal has a data editor or can be trivially be verified), "requested" (using language like "must" and "will"), "recommended" (encouraged, should) or leave empty if rule is not checked.

Feel free to add new rules if necessary.

**Comment by csokaimola** [comment]
I have finished.
- I added 4 new categories (package on journal website, pseudo-dataset, set seed, IRB for experiment), please review
- If I was not sure, I put a "?", please check these fields
- Other comment: I think categories "Include Raw Experimental Data" and "Include Raw Survey Data" are redundant, since these are just a subset of "Include Raw Data if Permissible", and always has the same value as "Include Raw Data if Permissible" (except when there is no explicit mention about experiment and survey in DAP, but still, if DAP says to include all raw data, then it means experiment and survey data as well). Same logic applies in case of "Include Code for Experiment" and "Include Code for Simulations", I find these 2 also redundant since "Include Analysis Code" says it all.
