### ISSUE TITLE
Compare to Lars's matrix

### ISSUE THREAD

**Issue by korenmiklos** [REStud/guidance#6]
https://docs.google.com/spreadsheets/d/10vM8lbxaLVW-1ES_cSsTWzuqwk8lmlTxNq2J74Ab8cs/edit#gid=1415770916

**Comment by csokaimola** [comment]
Lars already did the comparison on sheet "Mapping to RDPF". I left a comment (correction) in B13 because DAP is included in 11(b) of Reproducible Research Standard v1.0.
I already did this with (DAP matrix)[https://docs.google.com/spreadsheets/d/11lua0_5iE-ioX0H-90oUM-ZdfYkZCMBHjAHIpC2ZYds/edit#gid=1572747753], and on sheet "Recommendation" I crated a Category called "Exceptions" with the Roles "Exceptions" and "Contact of support" which could cover RDPF2 and 8.
